-- Verify existence, columns, and indexes for public.averbacoes_gratuitas

-- 1) Table exists
SELECT to_regclass('public.averbacoes_gratuitas') AS table_exists;

-- 2) Columns overview
SELECT 
    column_name, data_type, is_nullable, column_default
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'averbacoes_gratuitas'
ORDER BY ordinal_position;

-- 3) Indexes
SELECT indexname, indexdef
FROM pg_indexes
WHERE schemaname = 'public' AND tablename = 'averbacoes_gratuitas'
ORDER BY indexname;

-- 4) Safe insert test in a transaction (ROLLBACK so no data persists)
BEGIN;
INSERT INTO public.averbacoes_gratuitas (data, tipo, ressarcivel, livro, folha, termo)
VALUES (CURRENT_DATE, 'OUTROS', FALSE, 'A', '1', '123');
-- Fetch id generated by the sequence (works for BIGSERIAL)
SELECT currval(pg_get_serial_sequence('public.averbacoes_gratuitas', 'id')) AS last_id;
ROLLBACK;