<#
scripts/test_presign_cors.ps1
Simple helper to run CORS preflight (OPTIONS) and an optional PUT against a presigned URL.
Usage (PowerShell):
  .\scripts\test_presign_cors.ps1 -Url "<PRESIGNED_URL>" -Origin "https://www.bibliofilia.com.br" -FilePath ".\tmp.bin"

Parameters:
  -Url      : (required) Presigned PUT URL generated by the backend
  -Origin   : Origin value to send in the preflight (defaults to production origin)
  -FilePath : Optional local file path to upload with PUT (if omitted, PUT step is skipped)
#>

param(
  [Parameter(Mandatory=$true)][string]$Url,
  [string]$Origin = 'https://www.bibliofilia.com.br',
  [string]$FilePath = ''
)

function dump-headers($hdrs){
  if (-not $hdrs) { return }
  $hdrs.GetEnumerator() | ForEach-Object { Write-Host ("{0}: {1}" -f $_.Key, $_.Value) }
}

Write-Host "Running CORS preflight (OPTIONS) against:`n  $Url`n  Origin: $Origin`n"
$optsHeaders = @{
  'Origin' = $Origin
  'Access-Control-Request-Method' = 'PUT'
  'Access-Control-Request-Headers' = 'Content-Type,Authorization'
}

try {
  $optsResp = Invoke-WebRequest -Uri $Url -Method Options -Headers $optsHeaders -UseBasicParsing -TimeoutSec 30
  $status = $optsResp.StatusCode 2>$null
  if (-not $status) { $status = $optsResp.StatusDescription 2>$null }
  Write-Host "OPTIONS response status: $status"
  Write-Host "Response headers:"; dump-headers $optsResp.Headers
} catch {
  Write-Host "OPTIONS request failed:"
  if ($_.Exception.Response -ne $null) {
    try { $code = $_.Exception.Response.StatusCode; Write-Host "Status: $code" } catch {}
    try { $rheaders = $_.Exception.Response.Headers; Write-Host "Response headers:"; dump-headers $rheaders } catch {}
  }
  Write-Host "Exception message:" $_.Exception.Message
}

if ($FilePath -and (Test-Path $FilePath)) {
  Write-Host "`nPerforming PUT with file: $FilePath"
  try {
    $putHeaders = @{ 'Content-Type' = 'application/octet-stream' }
    $putResp = Invoke-WebRequest -Uri $Url -Method Put -InFile $FilePath -Headers $putHeaders -UseBasicParsing -TimeoutSec 120
    $pstatus = $putResp.StatusCode 2>$null
    if (-not $pstatus) { $pstatus = $putResp.StatusDescription 2>$null }
    Write-Host "PUT response status: $pstatus"
    Write-Host "PUT response headers:"; dump-headers $putResp.Headers
  } catch {
    Write-Host "PUT failed:" $_.Exception.Message
    if ($_.Exception.Response -ne $null) {
      try { $code = $_.Exception.Response.StatusCode; Write-Host "Status: $code" } catch {}
      try { $rheaders = $_.Exception.Response.Headers; Write-Host "Response headers:"; dump-headers $rheaders } catch {}
    }
  }
} elseif ($FilePath) {
  Write-Host "File not found: $FilePath - skipping PUT step."
} else {
  Write-Host "PUT step skipped (no -FilePath provided)."
}
